### ISSUE TITLE
assist pipeline frozen and "No transcription received" error in HA log 

### ISSUE THREAD

**Issue by reinholdPL** [fabio-garavini/ha-openai-whisper-stt-api#5]
everything was working great and suddenly assist pipeline has frozen on `Speech-to-text` part (with loading circle still spinning). In home assistant log I can see `No transcription received` error.

```
Rejestrator: custom_components.openai_whisper_cloud.const
Źródło: custom_components/openai_whisper_cloud/stt.py:171
integracja: Whisper Cloud ([dokumentacja](https://github.com/fabio-garavini/ha-openai-whisper-stt-api), 
```

last part of raw debug data from debug:

```
stt:
  engine: stt.groqcloud_whisper
  metadata:
    language: pl
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: false
```

and it's been like that for two hours.  I apologize in advance because I'm not quite sure if it's not some problem on my home assistants side. Shouldn't it handle errors like that?
